#! /bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Concatenate several XML files into a stream.
#**

set -ue;

# In its simplest form, we just cat the files:

cat ${1+"$@"}
