#! /bin/sh
#!perl --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Split convcatenated XML file stream into separate XML files. Each
#  resulting file will be well-formed if the original files were
#  well-formed before concatenation.
#**

use strict;
use warnings;

BEGIN {
    use Cwd qw(abs_path);
    my $base_dir = abs_path(__FILE__);
    $base_dir =~ /(.*)\/[^\/]+$/;
    $base_dir = $1;
    $base_dir =~ s/\/(?:bin|scripts)$//;
    push(@INC, $base_dir . "/lib/perl5");
    push(@INC, $base_dir . "/externals/SOptions");
    push(@INC, $base_dir . "/externals/SUsage");
}

my $xml_head = '<?xml ';
local $/ = $xml_head;

while(<>) {
    s/\Q$xml_head\E$//;
    next if $_ eq "";
    print ">>>>\n";
    print $xml_head, $_;
    print "<<<<\n";
}
