#! /bin/sh
#!perl --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Split concatenated XML file stream into separate XML files and run
#  the peorgrams that is specified on the command line, in the manner
#  'xargs' does it for the arguments read from STDIN.
#**

use strict;
use warnings;

BEGIN {
    use Cwd qw(abs_path);
    my $base_dir = abs_path(__FILE__);
    $base_dir =~ /(.*)\/[^\/]+$/;
    $base_dir = $1;
    $base_dir =~ s/\/(?:bin|scripts)$//;
    push(@INC, $base_dir . "/lib/perl5");
    push(@INC, $base_dir . "/externals/SOptions");
    push(@INC, $base_dir . "/externals/SUsage");
}

use POSIX qw(sysconf);

use SOptions qw(getOptions);
use SUsage qw(usage);

my $arg_max = sysconf( &POSIX::_SC_ARG_MAX );

print ":::: \$arg_max = $arg_max\n";

my $xml_head = '<?xml ';

#* USAGE:
#*     $0 --options input1.xmlcat input*.xmlcat
#*     $0 --options < input.xmlcat
#* 
#* OPTIONS:
#*
#*    --help,--usage         Print a short usage message (this message) and exit.
#**

@ARGV = getOptions( 
    "--options" => sub { 
        print "$0: The '--options' option is a placehoder.\n";
        print "$0: It should be replaced by one of the following options:\n";
        ## SUsage::usage;
        open( SCRIPT, $0 ) or die $!;
        while( <SCRIPT> ) {
            if( /^#\*\s+OPTIONS:/../^#\*\*/ ) {
                s/^#\*\s+OPTIONS://;
                s/^#\*\*?\s+//;
                print;
            }
        }
        close( SCRIPT );
        exit
    },
    "--help,--usage" => sub { SUsage::usage; exit },
);

# The redefinition of '$/' must be done after the option processing,
# otherwise 'SUsage::usage', '--help' and '--options' options will not
# work as expected.

local $/ = $xml_head;

while(<>) {
    s/\Q$xml_head\E$//;
    next if $_ eq "";
    print ">>>>\n";
    print $xml_head, $_;
    print "<<<<\n";
}
